### ISSUE TITLE
Deserialize verursacht eine NullReferenceException

### ISSUE THREAD

**Issue by tomwendel** [tomwendel/octoawesome#108]
Im Stream von gestern haben wir leider die Deserialize Methode der Columns durch eine überschnelle Implementierung kaputt gemacht. Beim deserialisieren der ChangeCounter greifen wir auf eine Liste von noch nicht initialisierten Chunks zu -> peng!

ChunkColumn.cs, Zeile 310

Das muss entweder zu einem späteren Zeitpunkt passieren oder wir müssen die Werte zwischenspeichern um sie erst später, nach dem Initialisieren der Chunks, an die richtigen Stellen zu schreiben.

**Comment by ManuelHu** [comment]
Deserialisieren funktioniert mittlerweile wieder. Close?

**Comment by tomwendel** [comment]
Stimmt.
