### ISSUE TITLE
Inventar Exception bei Blöcken

### ISSUE THREAD

**Issue by CsharpLassi** [tomwendel/octoawesome#18]
bei Blöcken im Inventar gibt es beim öffnen des Inventars eine Null-Exception

**Comment by tomwendel** [comment]
Ohjeh. Da gibt es noch einiges zu fixen nach unserem Umbau. Da stolpern wir sicher in den kommenden Folgen drüber

**Comment by lightslider** [comment]
Das Problem liegt im Actorhost bei Block Interaction. Du setzt die Definition für einen neuen Block auf Null. Obendrüber steht ein TODO mit der Notiz :D

**Comment by tomwendel** [comment]
Gefixt in Folge 236 oder so.
