### ISSUE TITLE
Inventar-Stacks des gleichen Typs sorgen für Exception

### ISSUE THREAD

**Issue by tomwendel** [tomwendel/octoawesome#23]
Submit von Manuel:

In ActorHost.cs, Zeile 236ff. holst du dir mit SingleOrDefault den Slot, generierst aber darunter unter bestimmten Bedingungen (Slot voll) einen neune Slot für die gleiche Definition. Dann läuft aber SingleOrDefault in eine Exception. Deshalb solltest du

SingleOrDefault(s => s.Definition == blockDefinition)

mit

Where(s => s.Definition == blockDefinition && s.Amount <
blockDefinition.StackLimit).FirstOrDefault()

**Comment by CsharpLassi** [comment]
Hab ein Pull-Request für den Bug angelegt.
