### ISSUE TITLE
OctoAwesome.Database ITag code duplication

### ISSUE THREAD

**Issue by jvbsl** [tomwendel/octoawesome#301]
Die Methode GetBytes in ITag des OctoAwesome.Database Projektes ist duplizierter Code.
https://github.com/OctoAwesome/octoawesome/blob/9f76ddb489298f7eb76d1eca51f3321ed2c187a3/OctoAwesome/OctoAwesome.Database/ITag.cs#L9

Evtl. stattdessen über die Methode WriteBytes implementieren.

**Comment by susch19** [comment]
Duplikat von #307
