### ISSUE TITLE
OctoAwesome.Database ITag Span benutzen anstelle von Array

### ISSUE THREAD

**Issue by jvbsl** [tomwendel/octoawesome#302]
In ITag in OctoAwesome.Database Projekt kann anstelle von Byte-Array ein Span benutzt werden:
https://github.com/OctoAwesome/octoawesome/blob/9f76ddb489298f7eb76d1eca51f3321ed2c187a3/OctoAwesome/OctoAwesome.Database/ITag.cs#L10

Für das eventuelle verhindern von Allokationen bzw. beliebige Wahl des Memory bereichs.

**Comment by susch19** [comment]
Duplikat von #307
