### ISSUE TITLE
Player Position immer 5 Blöcke zu tief

### ISSUE THREAD

**Issue by ManuelHu** [tomwendel/octoawesome#31]
Der Player landet immer 5 Blöcke unterhalb der gesetzten Position.

Zum Beispiel steht
```csharp
Position = new Coordinate(0, new Index3(10, 10, 50), Vector3.Zero);
```
im Code.

Nach dem Starten stehe ich aber sofort am Block 10/10/45. Auch bei den serilialisierten Daten lande ich immer die 5 Blöcke tiefer und damit im Boden.

Eventuell ist noch hilfreich, dass die zu kleine Position noch während der Anzeige des Menüs gesetzt wird.

**Comment by fnawratil** [comment]
In der neusten Version vorübergehend gefixt --> Muss noch angepasst werden

**Comment by tomwendel** [comment]
Mh. Klingt, als ob der Spieler durch den noch nicht geladenen Chunk fällt... Wird Zeit für einen Loading-Screen

**Comment by ManuelHu** [comment]
WorldStates haben wir ja schon implementiert. Wir setzen sie aber nur auf Running und machen sonst nix damit. Vielleicht sollte man schon beim MainScreen anfangen, die Chunks im Hintergrund zu laden, den State aber erst auf Running setzen, wenn auf den Button gecklickt wird. Natürlich muss dann auch in allen UpdateLoops konsequent nichts getan werden, wenn der State noch auf Loading steht.

**Comment by fnawratil** [comment]
Im Zuge dessen lässt sich auch einfach ein Pause Screen implementieren...

**Comment by tomwendel** [comment]
Gefixt mit Commit zu Folge 275
