### ISSUE TITLE
Selektion über Datumsgrenze hinweg mal wieder kaputt :(

### ISSUE THREAD

**Issue by tomwendel** [tomwendel/octoawesome#35]
Leider funktioniert die Selektion und Bearbeitung von Blocks über die Datumsgrenze hinweg mal wieder nicht. Wüsste zwar nicht was wir kaputt gemacht haben, aber nun ja...

**Comment by SanseroGames** [comment]
Die Kollision ist an der Datumsgrenze ebenfalls kapputt. Wenn ich über die datumsgrenze gehe, kann ich mich in einen Block glitchen. Ich kann auch an der Position 0/0 ein ein Block grosses Loch machen und hineinfallen. an anderen Stellen ist dies nur bei einem zweimalzwei Block grossen Loch möglich.
Ich vermute mal stark, dass das zusammenhängt.

**Comment by tomwendel** [comment]
Gefixt mit Commit zu Folge 276
