### ISSUE TITLE
Bewegung wird geblockt

### ISSUE THREAD

**Issue by fnawratil** [tomwendel/octoawesome#40]
In der neusten Version kann es, wenn man einige Chunks weit fliegt, passieren, dass der Cache die Chunks nicht schnell genug nachlädt (glaube ich), und daher jegliche Bewegung geblockt wird...
Input usw. geht

![image](https://cloud.githubusercontent.com/assets/10145306/11163805/69c89fd4-8add-11e5-8920-96c6af6b32a4.png)

Mfg rave

**Comment by CsharpLassi** [comment]
Kann ich nur bestätigen ^^

**Comment by CsharpLassi** [comment]
Das Problem liegt in der Updatemethode vom Actorhost an der Stelle an der der readyState auf false gesetzt werden kann.

PullRequest angelegt

**Comment by tomwendel** [comment]
Hab nen Fix gemacht der das Problem theoretisch beheben sollte. Ich lasse den Bug trotzdem mal offen, kann das Phänomen aktuell aber nicht mehr reproduzieren.

**Comment by fnawratil** [comment]
Nicht reproduzierbar
