### ISSUE TITLE
Korrupte Chunk Dateien blockieren das ganze Spiel

### ISSUE THREAD

**Issue by ManuelHu** [tomwendel/octoawesome#53]
Irgendwie wird, wenn ich Map-Daten im Verzeishnis habe, der ActorHost komplett geblockt. Die Anzeige bleibt bei Loaded Chunks: 2 stehen. Ohne Map-Verzeischnis funktioniert wieder alles einwandfrei.

**Comment by fnawratil** [comment]
Du meinst wenn das Verzeichnis von D:/OctoMap geändert wird? Dann muss da noch irgendwo ne hardcoded Referenz sein...

**Comment by ManuelHu** [comment]
Nö. Spiel blockt bei mir komplett, wenn irgendwas im OctoMap-Directory ist.

**Comment by tomwendel** [comment]
mh. kann ich leider nicht ganz reproduzieren. Sind die Files vielleicht durch eine zweite Instanz geblockt? Sagt der Debugger was?

**Comment by ManuelHu** [comment]
<del>Anscheinend wird der Ready-State nicht auf true gesetzt, deshalb wird der ActorHost gar nicht geupdated (Steuerung geht nicht). Im LocalChunkCache.InternalSetCenter ermittelt er auch 72 benötigte Chunks.</del> Das passiert, wenn der Serializer ungewollt beendet wird (z.B. ducrch VS) und deshalb eine korrupte Datei erstellt. Der Deserializer landet irgendwie in einer Endlosschleife und blockt dadurch das ganze Spiel.

**Comment by tomwendel** [comment]
Mhhh. Das ist interessant. Eigentlich sollte unser Deserializer mit Exceptions um sich werfen wenn das Format kaputt ist und die ganze Applikation in den Abgrund reißen. Was immer noch besser wäre als ein Freeze. Gibts denn vielleicht Exceptions und wir fangen die nur irgendwo doof ab? Das könnte ich mir nämlich vorstellen :D

**Comment by ManuelHu** [comment]
Nö es gibt keine Exception. Zumindest keine die in VS (Dieses Fenster im Code) angezeigt wird oder bei der das Spiel abstürzt. Im Ausgabefenster steht nur:
```
Ausnahme ausgelöst: "System.IO.EndOfStreamException" in mscorlib.dll
```
Im ChunkSerializer werden übrigens keine Exceptions von uns geworfen, wenn das Format stimmt...

Zur Reproduktion: Einfach in Notepad++ oder so (Editor mit Binary Unterstützung) irgendwo in der Datei Daten entfernen.

**Comment by tomwendel** [comment]
Da das ist doch eine Exception :) läääuft!
Im Idealfall würde ich diesen Chunk dann einfach ignorieren und ggf. eine Log-Info raus hauen

**Comment by ManuelHu** [comment]
Hat mich nur irritiert, dass die nur im Ausgabefenster angezeigt eird, obwohl nicht gecatcht. Ein einfacher 
```csharp
try
{
    ...
} 
catch 
{ 
    return null;
}
```
ums Deserialize würds eigentlich doch tun, oder? Eventuell noch die korrupte Datei löschen, sonst wird der Chunk auch nicht vom MapGenerator neu generiert.

**Comment by fnawratil** [comment]
Um das ganze mal neu aufleben zu lassen: Wie wärs mit Checksums?

**Comment by ManuelHu** [comment]
Ich weiß nicht, ob Checksums der richtige Weg sind, um dem Problem beizukommen. Das Programm versucht über das Ende des Streams zu lesen, auch mit Checksums müsste man zuerst die Daten lesen und dann überprüfen (mein Halbwissen - geht vielleicht doch anders?).
Erstmal geht es darum korrupte Chunks auszusortieren und neuzugerieren, wenn ein Fehler in der Datei ist => try/catch mit Datei umbenennen/löschen. Checksums können vielleicht später benutzt werden, um Antworten vom Server zu prüfen, ...

**Comment by tomwendel** [comment]
Ich schließe mich Manuel an. Checksums würden uns zwar erlauben Manipulationen zu erkennen, bringt uns aber bei diesem Problem keinen wirklichen Vorteil gegenüber dem Try/Catch der bisherigen Lösung.

Checksums für die Prüfung der Serverantworten können wir uns im Grunde sparen. Wir verwenden TCP. Wenn da die Daten kaputt sind, läuft was ganz anderes schief. Interessant könnte es damit aber werden, wenn es darum geht herauszufinden, ob sich der Chunk seit dem letzten Client-Update geändert hat oder nicht. Also das, was wir gerade mit einem fortlaufenden Counter in den Chunk-Renderern machen.

**Comment by ManuelHu** [comment]
> dem Try/Catch der bisherigen Lösung.

Ähhm, hab ich da was verpasst? Im master-Branch sind da keine try/cathe-Blöcke. Ein bloßes 
```csharp
catch 
{ 
    return null;
}
```
im Deserializer reicht vermutlich aus. Einmal hat das Spiel für diesen Chunk keine Änderungen mehr serialiert, war jetzt grad aber nicht mehr reproduzierbar.

**Comment by tomwendel** [comment]
Hehe. Ja. der aktuelle Code ist natürlich noch nicht optimal. Aber was ich meinte ist, dass meiner Meinung nach ein try/catch um den Deserialize-Code reicht. Sollte der Deserialize fehlschlagen, muss der kaputte Chunk aber noch gelöscht werden - das fehlt aktuell.

**Comment by tomwendel** [comment]
Inzwischen ja behoben...
