### ISSUE TITLE
Neue Features in C# 6 machen Probleme mit Mono

### ISSUE THREAD

**Issue by fnawratil** [tomwendel/octoawesome#65]
z.B. im PlayerComponent wird eine Property inline initialisiert, ein Feature das erst mit C# 6 eingeführt wurde und Probleme mit der aktuellen version des Mono-Compilers machen.

Beispiel:
public bool[] SlotInput { get; private set; } = new bool[10];

Mfg rave

**Comment by jvbsl** [comment]
Was genau macht denn dabei Probleme? Compiler-Fehler?
Denn bei mir scheint das wunderbar zu funktionieren.

**Comment by fnawratil** [comment]
Compiler-Fehler, ja... Ich muss nochmal schauen welche Mono-Version ich verwendet hab, aber er schmeisst immer Fehler bei den betreffenden Zeilen...

**Comment by fnawratil** [comment]
http://www.mono-project.com/docs/about-mono/languages/csharp/

Ich verwend nicht die 3.8 Preview, und hab Mono auch nicht selbst gebuilded...

**Comment by jvbsl** [comment]
"The latest Mono release is: 4.2 Stable (4.2.1.102)"
und genau die hab ich auch, aus den mono-repositories:
http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives
Die Ubuntu-Repositories beinhalten natürlich eine Uralt-version

**Comment by fnawratil** [comment]
Hmm... :/ Ich Versuchs nochmal mit der aktuellsten Version

**Comment by tomwendel** [comment]
Hab befürchtet, dass uns das früher oder später Probleme macht. Lasst mich mal wissen was man so an gängigen Tools verwendet und ob euch das Ärger macht. Aus meiner Sicht können wir vorerst gerne auf C# 6.0 verzichten ;)

**Comment by fnawratil** [comment]
Mit der aktualisierten Version gehts. Danke!
Darauf verzichten nicht, wenns nicht unbedingt sein muss. Allein das $"..." für strings :heart_eyes:

**Comment by fnawratil** [comment]
Jetzt bekomm ich Probleme mit xbuild und den ResX Files...

**Comment by jvbsl** [comment]
Was für ResX files und wie wirkt sich das genau aus?

**Comment by CsharpLassi** [comment]
@jvbsl Visual Studio legt bei einem WinForms-Projekt eine *.ResX Datei an. Diese kann nicht automatisch kompelliert werden.

Aber in den meisten Projekten wird diese Datei nicht benötigt und kann daher auch gelöscht werden. Das Programm funktioniert dennoch.

**Comment by fnawratil** [comment]
@CsharpLassi
Das werd ich mal versuchen...
