### ISSUE TITLE
Git - aber richtig

### ISSUE THREAD

**Issue by fnawratil** [tomwendel/octoawesome#87]
Momentan ist das ganze Repo ja etwas durcheinander. Wir nutzen Master als den Stable-Branch, Network für ALLES und nebenbei gibt es noch Rendering als einzigen aufgeräumten Branch.
Das alles ist sehr unübersichtlich, und wird früher oder später zu großen Merge Problemen führen.

Ich schlage deshalb vor, das Repo ordentlich zu strukturieren, Feature-Branches auch wirklich nur für die jeweiligen Features zu verwenden, und kleinere Änderungen die kein Feature betreffen in den Master Branch zu pushen. (Mit Tags zum Beispiel kann man ja weiterhin Releases kennzeichnen)

Außerdem sollte vielleich einmal der Network-Branch rebased werden um später einen Fast-Forward Merge durchführen zu können ~~und/oder die Commits die nichts mit Networking zu tun haben in den Masterbranch verschoben werden (auch wenn das wohl ein riesiges Projekt wäre).~~ *Das wird ja leider nicht gehen, weil viele der folgenden Commits tlw. auch auf denen basieren*

Falls Bedarf besteht: https://www.atlassian.com/git/tutorials/
Mfg rave

**Comment by HendrikFW** [comment]
Ich hatte es ja schon mit ins Trello-Board aufgenommen: Wir brauchen einen einheitlichen Git-Workflow. 
Ich sehe kein Problem dabei den `Master` als Stable-Branch zu missbrauchen, würde aber einen `Develop` Branch anlegen indem die Features zusammenkommen. Die von dir angesprochenen Feature-Branches nutze ich beruflich ebenso und bin äußerst zufrieden mit dieser Vorgehensweise. 

Ich mache das z.z. so:
- master
- develop
- issue/xy (referenzier auf Issue#yx)
- ft/xz (referneziert auf Issue#yz, stellt aber neues Feature dar)

**Comment by m4cx** [comment]
Mit folgendem Branching-Modell habe ich gute Erfahrungen gemacht:
http://nvie.com/posts/a-successful-git-branching-model/

Ist dem ähnlich, was @HendrikFW beschreibt.

**Comment by ManuelHu** [comment]
Ihr mögt zwar alle recht haben, dass diese Methoden für "richtige" Programmierung gut geeignet sind und sich in der Praxis bewährt haben, ich meine aber, dass wir uns sowieso von den Branches abwenden sollten, weil
* In den Folgen gibt es ja auch keine Branches: In Folge x wird Feature xyz implementiert. In Folge x+1 wird Feature zyx implementiert. Man sieht dann aber nicht Feature xyz. das ist meiner Meniung nach problematisch, da es für die Zuschauer verwirrend ist und gleichzeitig die Motivation eines Fortschrittes fehlt.
* Punkt zwei fällt mir grade nicht mehr ein :-)

**Comment by m4cx** [comment]
Unter dem Gesichtspunkt wäre es dann sinnvoll die Entwicklung in einem develop-Branch (analog zu den Folgen) zu machen. 

Dann sollte man zu einem geeigneten Zeitpunkt, wenn man sicher ist, das alles soweit alles funktioniert, die Entwicklung in den master-Branch übertragen. 

Somit sind die Folgen für den Zuschauer nachvollziehbar und es kann ein stabiler Stand "veröffentlicht" werden, mit dem "alle" spielen können.

**Comment by fnawratil** [comment]
Das ist wahr...

Noch was anderes zu dem Thema:
@tomwendel
Wenn du die Lokalisierunge  in den Network branch mergest sparen wir uns conflicts.

Hab das mergen von network in master heute mal versucht: Viele Conflicts treten nur deswegen auf...

**Comment by tomwendel** [comment]
Jepp. Ich gebe euch vollkommen Recht. Das kann so nicht weiter gehen :D 

Der ursprüngliche Plan mit dem Network-Branch war es ja das Feature zu Ende zu implementieren und dann zu mergen. Das hätte am Ende von Folge 300 passieren müssen. Jetzt mische ich alles und das ist Quatsch.

Mein Ausweg: Schnellstmöglicher Merge aller Branches zu Master (wenn möglich stable) und ab dann den develop-Branch als laufenden Branch. Wenn wir das mit dem Projekt-Management wirklich ernst meinen, sollte der Merge nach jedem Feature auch keine größere Sache mehr darstellen.

Branches für einzelne Features zu erzeugen bringt nur Durcheinander. Ich sehe weitere Branches eigentlich nur, wenn mal jemand getrennt an anderen Features arbeitet. Julian z.B. mit einem erweiterten Map Generator.

Ich muss mir dringend dieses Tutorial rein ziehen... :-/ Weiß nicht wann. Im Notfall im Stream. Dann machen wir ein "Git-Special" damit ALLE das lernen und nicht nur ich.

**Comment by fnawratil** [comment]
Bevor Network in Master gemerged wird müssen wir erstmal ein "funktionierendes & performantes" networking implementieren. Das aktuelle geht ja ab 3-4 Clients nicht mehr richtig.

Ich würde daher den Network-Branch belassen und zusätzlich einen Develop-Branch erstellen, momentan halt für alle PullRequests. Sobald Network fertig ist wird er in develop gemerged.
Alternativ Network gleich in develop mergen oder zu develop umbenennen

**Comment by HendrikFW** [comment]
Ok ich sehe auch ein das wir es uns nicht allzu kompliziert machen müssen. Ich selber möchte Feature-Branches nicht mehr missen aber ich arbeite auch schon länger mit Git. 
Einen `Develop` für die Folgen und einen `Master` der immer bei stable-Releases gemergt wird finde ich gut. Trotzdem könnte man ja bei Bedarf auf einen `Feature-Branch` zurückgreifen wenn man solch gravierenden Änderungen plant wovon man voher noch nicht weis ob das überhaupt was wird.

**Comment by CsharpLassi** [comment]
ich kann vielen nur zustimmen. Und bin dafür das wir dem ganzen Chaos etwas struktur geben.
Mit den Branches müssen wir es ja nicht überteiben, aber master und develop sollte schon sein.

Wir müssten auch mal Regeln aufstellen die das Pullrequesten vereinfachen. 
Sowas wie 
->Pullrequest sollten auf develop mergen
->Neue Request müssen bis Mittwoch-Abend eingereicht werden und zur ersten Aufnahme mergen
->Wenn nicht gemergt wurden ist sollte darauf geachten werden das er zur nächsten Aufnahme mergt
->Auch Request mal zuückzeihen

viele grüße

**Comment by tomwendel** [comment]
Das Wort "Chaos" trifft mich jetzt schon ein bisschen :D Ganz so schlimm ist es ja nicht. Der network-Branch hat einfach nur den falschen Namen. Wir benennen den jetzt einfach mal um. Julian hat mir versichert, dass wir das ganz einfach hin bekommen

**Comment by fnawratil** [comment]
@tomwendel ich kann dir jetzt Erleichterung schaffen:
Visual Studio hat mit der Git Integration ein erstaunlich gutes diff- & mergetool.

Ich hab mich jetzt mal damit beschäftigt und bemerkt, dass es auch einfach möglich ist github pullrequests in visual studio zu mergen. (Keine ungelösten Conflicts mehr! :laughing: )

Ich könnte zwar schon mal mit in nen Stream dafür, bin aber halt auch kein Profi und kann nur das was ich brauche um mit git umzugehen...

**Comment by tomwendel** [comment]
Na das klingt doch seeeehr vielversprechend. Das Diff-Tool von VS ist nämlich gar nicht so schlecht. Gib mir gerne mal nen Hinweis was ich tun muss.

Und wegen des Streams lass dich nicht ärgern. Ich versuche ja immer auch die Leute in den Stream zu holen, die von uns allen die meisten Fähigkeiten zu einem Thema haben. Dabei gehts nicht darum perfekter Profi zu sein, sondern uns eher weiter zu bringen. Aber am Ende natürlich deine Entscheidung.

**Comment by fnawratil** [comment]
Den Hinweis geb ich gerne, du musst allerdings die konsole für zwei commands verwenden :P

Wenn jemand einen neuen Pull Request stellt sitzt der in einem Branch in dem GitHub Repo der Person.
Den Branch kannst du dir in einen temporären branch in dein lokales repo holen und dann in visualstudio mergen.
Den tempörären branch kannst du nacher wieder löschen. 
Sinn macht das ganze natürlich nur bei Conflicts, denn der PullRequest wird von Github nicht als gemerged erkannt und muss händisch geschlossen werden.

Du gehst also folgendermaßen vor: 
Angenommen ich stelle einen PR aus meinem branch "Vulkan" erstellst du erst einen neuen temporären branch: 
`git checkout -b temp`
dann pullst du meinen "Vulkan" Branch in den temp branch:
`git pull http://www.github.com/fnawratil/octoawesome Vulkan`
Der Temp Branch sollte dir in VisualStudio dann richtig angezeigt werden, und du solltest mit rechtsklick mergen können...

**Comment by fnawratil** [comment]
Ich schlag übrigens noch was vor: PullRequests sollten nur mehr einen Commit enthalten!
Als PR Ersteller kann man seine einzelnen commits vor dem erstellen des PRs noch in einen Commit zusammenfassen.
Das hält die Timeline etwas sauberer und übersichtlicher...

**Comment by tomwendel** [comment]
Oh. eine interessante Lösung. Das würde dann aber den Urheber nicht integrieren - das wäre ganz besonders schade. Ich finds nämlich richtig cool, dass Leute dann als Contributor angezeigt werden. Würde ich also wirklich nur im "Notfall" machen.

Und ein Commit pro PR macht richtig viel Sinn. Ich würde noch ergänzen: Nur ein Feature pro Commit. Manchmal sind nämlich gute und schlechte Änderungen in einem PR zusammen. Das ist dann immer etwas doof

**Comment by fnawratil** [comment]
Der Urheber sollte eigentlich schon integriert werden, der Merge Commit gibt ja nur den Merge an, soweit ich weiß erscheint der commit des urhebers vor dem merge commit in der timeline...
Das müsste man aber mal ausprobieren...

**Comment by ManuelHu** [comment]
Das geht auch anders:

1. In der Kommandozeile führe folgenden Befehl aus `git remote add <username> https://github.com/<username>/octoawesome.git`. Das musst du nur einmal am Anfang machen, solange du den Ordner nicht löschst. (`<username>` natürlich mit dem GitHub-Benutzernamen austauschen)
1. In Visualstudio kannst du dann unter "Sync" im Menü "Fetchen" im unteren Dropdown-Menü den Remote `<username>` auswählen, dieser wird dann gefetcht.
![te-screenshot1](https://cloud.githubusercontent.com/assets/10050780/12866995/9e46292a-cce1-11e5-9b04-a6aedd136ba9.PNG)
1. Dann unter "Branches" Rechtsklick auf deinen _lokalen_ Branch (nicht unter remotes), "Mergen aus" auswählen und aus dem Dropdown den Branch aus dem remote-Repository des anderen Benutzers (z.B. `manuelhu/helpproject` wenn du den remote nach dem Benutzernamen benennst) auswählen.
![unbenannt](https://cloud.githubusercontent.com/assets/10050780/12867016/4ea7f3fc-cce2-11e5-9d00-b735960b82cc.PNG)

Hinweise:
* Ich habe das nicht wirklich ausprobiert
* Danach musst du die Conflicts beheben
* Nicht verwirren lassen, ich hatte keinen anderen remote als `upstream` zur Verfügung
