### ISSUE TITLE
Es fängt schon wieder an...

### ISSUE THREAD

**Issue by fnawratil** [tomwendel/octoawesome#93]
Dieses Savegame Zeugs hat aber nichts mehr mit Bäumen zu tun, oder lieg ich da falsch?
Wenn nein: Warum ist das in feature/trees?!

Mfg rave

**Comment by ManuelHu** [comment]
Für Bäume wurde ein neuer Welt-Teil (ChunkColumn) eingeführt. Dafür wurde dann eine neue Persistierungsstruktur entwickelt und in dem Zug gleich der Rest der Welt mitpersistiert.

**Comment by fnawratil** [comment]
Soweit ich das mitbekommen habe arbeiten wir jetzt doch an der Möglichkeit Welten zu laden, und daher auch an einer Überarbeitung der Architektur..

**Comment by ManuelHu** [comment]
Close? Ist ja schon in anderem Branch.
